"""add tables

Revision ID: 1b25c05c3b00
Revises: 
Create Date: 2025-04-05 17:52:52.739949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1b25c05c3b00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index('email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'created_at')
    op.add_column('waste_items', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('waste_items', sa.Column('pickup_date', sa.Date(), nullable=True))
    op.add_column('waste_items', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('waste_items', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('waste_items', 'item_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('waste_items', 'category',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('waste_items', 'status',
               existing_type=mysql.ENUM('pending', 'processing', 'recycled'),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.create_index(op.f('ix_waste_items_id'), 'waste_items', ['id'], unique=False)
    op.drop_constraint('waste_items_ibfk_1', 'waste_items', type_='foreignkey')
    op.create_foreign_key(None, 'waste_items', 'users', ['user_id'], ['id'])
    op.drop_column('waste_items', 'submitted_at')
    op.drop_column('waste_items', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waste_items', sa.Column('location', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('waste_items', sa.Column('submitted_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_constraint(None, 'waste_items', type_='foreignkey')
    op.create_foreign_key('waste_items_ibfk_1', 'waste_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_waste_items_id'), table_name='waste_items')
    op.alter_column('waste_items', 'status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('pending', 'processing', 'recycled'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('waste_items', 'category',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('waste_items', 'item_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('waste_items', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('waste_items', 'created_at')
    op.drop_column('waste_items', 'pickup_date')
    op.drop_column('waste_items', 'quantity')
    op.add_column('users', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('users', sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('email', 'users', ['email'], unique=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
